# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Social Data Analysis Assigment 2
email: s212784@student.dtu.dk, s212859@student.dtu.dk, s222751@student.dtu.dk
description: >- # this means to ignore newlines until "baseurl:"
  Crimes in San Francisco have been a concern for many years, and the city has been working to decrease their number. 
  In order to understand the pattern of crimes reported in the city, data from 2003 to 2017 was collected and analyzed. 
  The data includes various types of crimes such as theft, robbery, burglary, and vehicle theft, and was visualized using a variety of plots. 
  In this assignment. The first is a monthly time series plot about the number of crimes reported for each category,  the second is about 
  a map visualization for prostitution category for two specific time periods and the third is about a bar chart that shows the number of 
  crimes reported in each PdDistrict . We will explain in detail the key points in these plots to find out interesting patterns over the 
  aforementioned period.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
